name: Upload App SDK to PiPy

# Make a new release in the repo to build it. 
# This makes it work with trusted publishers.

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'  # Triggers when a version tag is pushed (e.g., v1.0.0)


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: |
        python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        verify-metadata: false
        repository-url: https://upload.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      env:
        ACTIONS_STEP_DEBUG: true  # Enables debug mode for this step

